// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Xenopairings.Data;

#nullable disable

namespace Xenopairings.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260608140151_AddIsTestEvent")]
    partial class AddIsTestEvent
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.DataProtection.EntityFrameworkCore.DataProtectionKey", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FriendlyName")
                        .HasColumnType("text");

                    b.Property<string>("Xml")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("DataProtectionKeys");
                });

            modelBuilder.Entity("Xenopairings.Models.Match", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("IsScored")
                        .HasColumnType("boolean");

                    b.Property<bool>("Player1BattleReady")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("Player1Id")
                        .HasColumnType("uuid");

                    b.Property<bool?>("Player1IsAttacker")
                        .HasColumnType("boolean");

                    b.Property<int?>("Player1PrimaryScore")
                        .HasColumnType("integer");

                    b.Property<int?>("Player1Score")
                        .HasColumnType("integer");

                    b.Property<int?>("Player1SecondaryScore")
                        .HasColumnType("integer");

                    b.Property<int?>("Player1SportsRating")
                        .HasColumnType("integer");

                    b.Property<string>("Player1TurnScoresJson")
                        .HasColumnType("text");

                    b.Property<bool?>("Player1WentFirst")
                        .HasColumnType("boolean");

                    b.Property<bool>("Player2BattleReady")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("Player2Id")
                        .HasColumnType("uuid");

                    b.Property<int?>("Player2PrimaryScore")
                        .HasColumnType("integer");

                    b.Property<int?>("Player2Score")
                        .HasColumnType("integer");

                    b.Property<int?>("Player2SecondaryScore")
                        .HasColumnType("integer");

                    b.Property<int?>("Player2SportsRating")
                        .HasColumnType("integer");

                    b.Property<string>("Player2TurnScoresJson")
                        .HasColumnType("text");

                    b.Property<Guid>("RoundId")
                        .HasColumnType("uuid");

                    b.Property<int>("TableNumber")
                        .HasColumnType("integer");

                    b.Property<Guid?>("TeamMatchupId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Player1Id");

                    b.HasIndex("Player2Id");

                    b.HasIndex("RoundId");

                    b.HasIndex("TeamMatchupId");

                    b.ToTable("Matches");
                });

            modelBuilder.Entity("Xenopairings.Models.Organization", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("InviteToken")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("InviteToken")
                        .IsUnique();

                    b.ToTable("Organizations");
                });

            modelBuilder.Entity("Xenopairings.Models.OrganizationMember", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("JoinedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("OrganizationId", "UserId")
                        .IsUnique();

                    b.ToTable("OrganizationMembers");
                });

            modelBuilder.Entity("Xenopairings.Models.Player", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ArmyFaction")
                        .HasColumnType("text");

                    b.Property<string>("ArmyList")
                        .HasColumnType("text");

                    b.Property<string>("EditToken")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<bool>("IsCheckedIn")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDropped")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("RegisteredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("TeamId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TournamentId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("EditToken")
                        .IsUnique();

                    b.HasIndex("OrganizationId");

                    b.HasIndex("TeamId");

                    b.HasIndex("TournamentId");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("Xenopairings.Models.PlayerRating", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("GamesPlayed")
                        .HasColumnType("integer");

                    b.Property<bool>("IsProfilePublic")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsVip")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("LastUpdated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("Rating")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("PlayerRatings");
                });

            modelBuilder.Entity("Xenopairings.Models.PlayerRatingHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double>("ActualOutcome")
                        .HasColumnType("double precision");

                    b.Property<int>("MyRawScore")
                        .HasColumnType("integer");

                    b.Property<string>("OpponentEmail")
                        .HasColumnType("text");

                    b.Property<string>("OpponentName")
                        .HasColumnType("text");

                    b.Property<int>("OpponentRawScore")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("PlayedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("PlayerRatingId")
                        .HasColumnType("uuid");

                    b.Property<double>("RatingAfter")
                        .HasColumnType("double precision");

                    b.Property<double>("RatingBefore")
                        .HasColumnType("double precision");

                    b.Property<Guid>("TournamentId")
                        .HasColumnType("uuid");

                    b.Property<string>("TournamentSlug")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TournamentTitle")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("PlayerRatingId");

                    b.ToTable("PlayerRatingHistories");
                });

            modelBuilder.Entity("Xenopairings.Models.PlayerReport", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("FiledAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsResolved")
                        .HasColumnType("boolean");

                    b.Property<string>("OrganizerNote")
                        .HasColumnType("text");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ReportedPlayerId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ReporterPlayerId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TournamentId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ReportedPlayerId");

                    b.HasIndex("ReporterPlayerId");

                    b.HasIndex("TournamentId");

                    b.ToTable("PlayerReports");
                });

            modelBuilder.Entity("Xenopairings.Models.Round", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsComplete")
                        .HasColumnType("boolean");

                    b.Property<string>("MissionLayout")
                        .HasColumnType("text");

                    b.Property<int>("RoundNumber")
                        .HasColumnType("integer");

                    b.Property<Guid>("TournamentId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TournamentId", "RoundNumber")
                        .IsUnique();

                    b.ToTable("Rounds");
                });

            modelBuilder.Entity("Xenopairings.Models.Team", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CaptainPlayerId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("InviteToken")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("TournamentId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("InviteToken")
                        .IsUnique();

                    b.HasIndex("TournamentId");

                    b.ToTable("Teams");
                });

            modelBuilder.Entity("Xenopairings.Models.TeamMatchup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoundId")
                        .HasColumnType("uuid");

                    b.Property<int>("TableGroupStart")
                        .HasColumnType("integer");

                    b.Property<Guid>("Team1Id")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("Team2Id")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RoundId");

                    b.HasIndex("Team1Id");

                    b.HasIndex("Team2Id");

                    b.ToTable("TeamMatchups");
                });

            modelBuilder.Entity("Xenopairings.Models.TopCutMatch", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("BracketRound")
                        .HasColumnType("integer");

                    b.Property<bool>("IsScored")
                        .HasColumnType("boolean");

                    b.Property<int>("MatchNumber")
                        .HasColumnType("integer");

                    b.Property<Guid?>("Player1Id")
                        .HasColumnType("uuid");

                    b.Property<int?>("Player1Score")
                        .HasColumnType("integer");

                    b.Property<Guid?>("Player2Id")
                        .HasColumnType("uuid");

                    b.Property<int?>("Player2Score")
                        .HasColumnType("integer");

                    b.Property<int>("Seed1")
                        .HasColumnType("integer");

                    b.Property<int>("Seed2")
                        .HasColumnType("integer");

                    b.Property<Guid>("TournamentId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("WinnerId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Player1Id");

                    b.HasIndex("Player2Id");

                    b.HasIndex("TournamentId");

                    b.ToTable("TopCutMatches");
                });

            modelBuilder.Entity("Xenopairings.Models.Tournament", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("ArmyListLocked")
                        .HasColumnType("boolean");

                    b.Property<bool>("CheckInEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsPrivate")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsTeamEvent")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsTestEvent")
                        .HasColumnType("boolean");

                    b.Property<string>("ManageToken")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("MaxPlayers")
                        .HasColumnType("integer");

                    b.Property<int>("NumberOfRounds")
                        .HasColumnType("integer");

                    b.Property<string>("OrganizerEmail")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OrganizerName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("RegistrationOpen")
                        .HasColumnType("boolean");

                    b.Property<int>("ScoringSystem")
                        .HasColumnType("integer");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("StartsAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int?>("TeamSize")
                        .HasColumnType("integer");

                    b.Property<string>("TiebreakersJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TimeZoneId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("TopCutSize")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ManageToken")
                        .IsUnique();

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Tournaments");
                });

            modelBuilder.Entity("Xenopairings.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EmailVerificationToken")
                        .HasColumnType("text");

                    b.Property<bool>("EmailVerified")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsVip")
                        .HasColumnType("boolean");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordResetToken")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("PasswordResetTokenExpiry")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Xenopairings.Models.Match", b =>
                {
                    b.HasOne("Xenopairings.Models.Player", "Player1")
                        .WithMany()
                        .HasForeignKey("Player1Id")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Xenopairings.Models.Player", "Player2")
                        .WithMany()
                        .HasForeignKey("Player2Id")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Xenopairings.Models.Round", "Round")
                        .WithMany()
                        .HasForeignKey("RoundId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Xenopairings.Models.TeamMatchup", "TeamMatchup")
                        .WithMany()
                        .HasForeignKey("TeamMatchupId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Player1");

                    b.Navigation("Player2");

                    b.Navigation("Round");

                    b.Navigation("TeamMatchup");
                });

            modelBuilder.Entity("Xenopairings.Models.OrganizationMember", b =>
                {
                    b.HasOne("Xenopairings.Models.Organization", "Organization")
                        .WithMany("Members")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Xenopairings.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Organization");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Xenopairings.Models.Player", b =>
                {
                    b.HasOne("Xenopairings.Models.Organization", "Organization")
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Xenopairings.Models.Team", "Team")
                        .WithMany("Players")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Xenopairings.Models.Tournament", "Tournament")
                        .WithMany()
                        .HasForeignKey("TournamentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Organization");

                    b.Navigation("Team");

                    b.Navigation("Tournament");
                });

            modelBuilder.Entity("Xenopairings.Models.PlayerRatingHistory", b =>
                {
                    b.HasOne("Xenopairings.Models.PlayerRating", "PlayerRating")
                        .WithMany()
                        .HasForeignKey("PlayerRatingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PlayerRating");
                });

            modelBuilder.Entity("Xenopairings.Models.PlayerReport", b =>
                {
                    b.HasOne("Xenopairings.Models.Player", "ReportedPlayer")
                        .WithMany()
                        .HasForeignKey("ReportedPlayerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Xenopairings.Models.Player", "ReporterPlayer")
                        .WithMany()
                        .HasForeignKey("ReporterPlayerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Xenopairings.Models.Tournament", "Tournament")
                        .WithMany()
                        .HasForeignKey("TournamentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ReportedPlayer");

                    b.Navigation("ReporterPlayer");

                    b.Navigation("Tournament");
                });

            modelBuilder.Entity("Xenopairings.Models.Round", b =>
                {
                    b.HasOne("Xenopairings.Models.Tournament", "Tournament")
                        .WithMany()
                        .HasForeignKey("TournamentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tournament");
                });

            modelBuilder.Entity("Xenopairings.Models.Team", b =>
                {
                    b.HasOne("Xenopairings.Models.Tournament", "Tournament")
                        .WithMany()
                        .HasForeignKey("TournamentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tournament");
                });

            modelBuilder.Entity("Xenopairings.Models.TeamMatchup", b =>
                {
                    b.HasOne("Xenopairings.Models.Round", "Round")
                        .WithMany()
                        .HasForeignKey("RoundId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Xenopairings.Models.Team", "Team1")
                        .WithMany()
                        .HasForeignKey("Team1Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Xenopairings.Models.Team", "Team2")
                        .WithMany()
                        .HasForeignKey("Team2Id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Round");

                    b.Navigation("Team1");

                    b.Navigation("Team2");
                });

            modelBuilder.Entity("Xenopairings.Models.TopCutMatch", b =>
                {
                    b.HasOne("Xenopairings.Models.Player", "Player1")
                        .WithMany()
                        .HasForeignKey("Player1Id")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Xenopairings.Models.Player", "Player2")
                        .WithMany()
                        .HasForeignKey("Player2Id")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Xenopairings.Models.Tournament", "Tournament")
                        .WithMany()
                        .HasForeignKey("TournamentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player1");

                    b.Navigation("Player2");

                    b.Navigation("Tournament");
                });

            modelBuilder.Entity("Xenopairings.Models.Organization", b =>
                {
                    b.Navigation("Members");
                });

            modelBuilder.Entity("Xenopairings.Models.Team", b =>
                {
                    b.Navigation("Players");
                });
#pragma warning restore 612, 618
        }
    }
}
